curl -X GET http://localhost:3060/public/contacto/informacion

###

curl -X POST http://localhost:3060/public/contacto/enviar-mensaje \
  -H "Content-Type: application/json" \
  -d '{"nombre":"Juan Pérez","email":"juan@test.com","telefono":"76543210","asunto":"Consulta sobre productos","mensaje":"Me gustaría saber más información sobre los productos para perros."}'

###
curl -X GET http://localhost:3060/public/info/faqs


