export enum PermisoEnum {
  // ==========================
  // Admin - Seguridad
  // ==========================
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_CREAR = 'USUARIOS_CREAR',
  USUARIOS_EDITAR = 'USUARIOS_EDITAR',
  USUARIOS_EDITAR_CONTRASENIA = 'USUARIOS_EDITAR_CONTRASENIA',
  USUARIOS_ELIMINAR = 'USUARIOS_ELIMINAR',

  // Roles
  ROLES_VER = 'ROLES_VER',
  ROLES_CREAR = 'ROLES_CREAR',
  ROLES_EDITAR = 'ROLES_EDITAR',
  ROLES_ELIMINAR = 'ROLES_ELIMINAR',
  ROLES_ASIGNAR_PERMISOS = 'ROLES_ASIGNAR_PERMISOS',

  PERMISOS_VER = 'PERMISOS_VER',
  PERMISOS_CREAR = 'PERMISOS_CREAR',
  PERMISOS_EDITAR = 'PERMISOS_EDITAR',
  PERMISOS_ELIMINAR = 'PERMISOS_ELIMINAR',

  // Empleados
  EMPLEADOS_VER = 'EMPLEADOS_VER',
  EMPLEADOS_CREAR = 'EMPLEADOS_CREAR',
  EMPLEADOS_EDITAR = 'EMPLEADOS_EDITAR',
  EMPLEADOS_ELIMINAR = 'EMPLEADOS_ELIMINAR',
  EMPLEADOS_ASIGNAR_SUCURSAL = 'EMPLEADOS_ASIGNAR_SUCURSAL',

  CONFIGURACION_VER = 'CONFIGURACION_VER',
  CONFIGURACION_EDITAR = 'CONFIGURACION_EDITAR',

  // ==========================
  // Admin - Catálogo
  // ==========================
  CATEGORIAS_VER = 'CATEGORIAS_VER',
  CATEGORIAS_CREAR = 'CATEGORIAS_CREAR',
  CATEGORIAS_EDITAR = 'CATEGORIAS_EDITAR',
  CATEGORIAS_ELIMINAR = 'CATEGORIAS_ELIMINAR',

  TIPOS_PRODUCTO_VER = 'TIPOS_PRODUCTO_VER',
  TIPOS_PRODUCTO_CREAR = 'TIPOS_PRODUCTO_CREAR',
  TIPOS_PRODUCTO_EDITAR = 'TIPOS_PRODUCTO_EDITAR',
  TIPOS_PRODUCTO_ELIMINAR = 'TIPOS_PRODUCTO_ELIMINAR',

  PRODUCTOS_VER = 'PRODUCTOS_VER',
  PRODUCTOS_CREAR = 'PRODUCTOS_CREAR',
  PRODUCTOS_EDITAR = 'PRODUCTOS_EDITAR',
  PRODUCTOS_ELIMINAR = 'PRODUCTOS_ELIMINAR',

  BANCOS_VER = 'BANCOS_VER',
  BANCOS_CREAR = 'BANCOS_CREAR',
  BANCOS_EDITAR = 'BANCOS_EDITAR',
  BANCOS_ELIMINAR = 'BANCOS_ELIMINAR',

  CUENTAS_BANCARIAS_VER = 'CUENTAS_BANCARIAS_VER',
  CUENTAS_BANCARIAS_CREAR = 'CUENTAS_BANCARIAS_CREAR',
  CUENTAS_BANCARIAS_EDITAR = 'CUENTAS_BANCARIAS_EDITAR',
  CUENTAS_BANCARIAS_ELIMINAR = 'CUENTAS_BANCARIAS_ELIMINAR',

  IMAGENES_PRODUCTO_CREAR = 'IMAGENES_PRODUCTO_CREAR',
  IMAGENES_PRODUCTO_EDITAR = 'IMAGENES_PRODUCTO_EDITAR',
  IMAGENES_PRODUCTO_ELIMINAR = 'IMAGENES_PRODUCTO_ELIMINAR',

  INVENTARIOS_EDITAR = 'INVENTARIOS_EDITAR',

  // ==========================
  // Admin - Sucursales y Horarios
  // ==========================
  SUCURSALES_VER = 'SUCURSALES_VER',
  SUCURSALES_CREAR = 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR = 'SUCURSALES_EDITAR',
  SUCURSALES_ELIMINAR = 'SUCURSALES_ELIMINAR',

  HORARIOS_VER = 'HORARIOS_VER',
  HORARIOS_CREAR = 'HORARIOS_CREAR',
  HORARIOS_EDITAR = 'HORARIOS_EDITAR',
  HORARIOS_ELIMINAR = 'HORARIOS_ELIMINAR',

  // ==========================
  // Admin - Servicios informativos
  // ==========================
  SERVICIOS_VER = 'SERVICIOS_VER',
  SERVICIOS_CREAR = 'SERVICIOS_CREAR',
  SERVICIOS_EDITAR = 'SERVICIOS_EDITAR',
  SERVICIOS_ELIMINAR = 'SERVICIOS_ELIMINAR',

  IMAGENES_SERVICIO_VER = 'IMAGENES_SERVICIO_VER',
  IMAGENES_SERVICIO_CREAR = 'IMAGENES_SERVICIO_CREAR',
  IMAGENES_SERVICIO_EDITAR = 'IMAGENES_SERVICIO_EDITAR',
  IMAGENES_SERVICIO_ELIMINAR = 'IMAGENES_SERVICIO_ELIMINAR',

  // ==========================
  // Admin - Ventas y Entregas
  // ==========================
  PEDIDOS_VER = 'PEDIDOS_VER',
  PEDIDOS_CREAR = 'PEDIDOS_CREAR',
  PEDIDOS_EDITAR = 'PEDIDOS_EDITAR',
  PEDIDOS_ELIMINAR = 'PEDIDOS_ELIMINAR',
  PEDIDOS_CAMBIAR_ESTADO = 'PEDIDOS_CAMBIAR_ESTADO',

  ENTREGAS_VER = 'ENTREGAS_VER',
  ENTREGAS_CREAR = 'ENTREGAS_CREAR',
  ENTREGAS_EDITAR = 'ENTREGAS_EDITAR',
  ENTREGAS_ELIMINAR = 'ENTREGAS_ELIMINAR',
  ENTREGAS_CAMBIAR_ESTADO = 'ENTREGAS_CAMBIAR_ESTADO',

  // ==========================
  // Admin - Reservas
  // ==========================
  RESERVAS_VER = 'RESERVAS_VER',
  RESERVAS_CREAR = 'RESERVAS_CREAR',
  RESERVAS_EDITAR = 'RESERVAS_EDITAR',
  RESERVAS_ELIMINAR = 'RESERVAS_ELIMINAR',

  // ==========================
  // Admin - Contacto y Mensajes
  // ==========================
  CONTACTO_VER = 'CONTACTO_VER',
  CONTACTO_EDITAR = 'CONTACTO_EDITAR',
  CONTACTO_ELIMINAR = 'CONTACTO_ELIMINAR',

  // ==========================
  // Admin - Reseñas
  // ==========================
  RESENIAS_VER = 'RESENIAS_VER',
  RESENIAS_CREAR = 'RESENIAS_CREAR',
  RESENIAS_EDITAR = 'RESENIAS_EDITAR',
  RESENIAS_ELIMINAR = 'RESENIAS_ELIMINAR',
  RESENIAS_MODERAR = 'RESENIAS_MODERAR',

  // ==========================
  // Cliente - Catálogo y navegación
  // ==========================
  CLIENTE_CATEGORIAS_VER = 'CLIENTE_CATEGORIAS_VER',
  CLIENTE_PRODUCTOS_VER = 'CLIENTE_PRODUCTOS_VER',
  CLIENTE_SERVICIOS_VER = 'CLIENTE_SERVICIOS_VER',

  // ==========================
  // Cliente - Perfil y seguridad
  // ==========================
  CLIENTE_PERFIL_VER = 'CLIENTE_PERFIL_VER',
  CLIENTE_PERFIL_EDITAR = 'CLIENTE_PERFIL_EDITAR',
  CLIENTE_CAMBIAR_PASSWORD = 'CLIENTE_CAMBIAR_PASSWORD',

  // ==========================
  // Cliente - Carrito
  // ==========================
  CLIENTE_CARRITO_VER = 'CLIENTE_CARRITO_VER',
  CLIENTE_CARRITO_AGREGAR = 'CLIENTE_CARRITO_AGREGAR',
  CLIENTE_CARRITO_ACTUALIZAR = 'CLIENTE_CARRITO_ACTUALIZAR',
  CLIENTE_CARRITO_ELIMINAR = 'CLIENTE_CARRITO_ELIMINAR',

  // ==========================
  // Cliente - Reservas
  // ==========================
  CLIENTE_RESERVAS_VER = 'CLIENTE_RESERVAS_VER',
  CLIENTE_RESERVAS_CREAR = 'CLIENTE_RESERVAS_CREAR',
  CLIENTE_RESERVAS_CANCELAR = 'CLIENTE_RESERVAS_CANCELAR',

  // ==========================
  // Cliente - Pedidos y compras
  // ==========================
  CLIENTE_PEDIDOS_VER = 'CLIENTE_PEDIDOS_VER',
  CLIENTE_PEDIDOS_CREAR = 'CLIENTE_PEDIDOS_CREAR',
  CLIENTE_PEDIDOS_CANCELAR = 'CLIENTE_PEDIDOS_CANCELAR',
  CLIENTE_ENTREGAS_VER = 'CLIENTE_ENTREGAS_VER',

  // ==========================
  // Cliente - Reseñas y contacto
  // ==========================
  CLIENTE_RESENIAS_CREAR = 'CLIENTE_RESENIAS_CREAR',
  CLIENTE_RESENIAS_EDITAR = 'CLIENTE_RESENIAS_EDITAR',
  CLIENTE_RESENIAS_ELIMINAR = 'CLIENTE_RESENIAS_ELIMINAR',
  CLIENTE_CONTACTO_CREAR = 'CLIENTE_CONTACTO_CREAR',

  // ==========================
  // Admin - Reportes
  // ==========================
  REPORTES_VER = 'REPORTES_VER',
}
