export enum PermisoEnum {
  // ==========================
  // Admin - Seguridad
  // ==========================
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_CREAR = 'USUARIOS_CREAR',
  USUARIOS_EDITAR = 'USUARIOS_EDITAR',
  USUARIOS_EDITAR_CONTRASENIA = 'USUARIOS_EDITAR_CONTRASENIA',
  USUARIOS_ELIMINAR = 'USUARIOS_ELIMINAR',
  ELIMINAR_USUARIOS_NO_VERIFICADOS = 'ELIMINAR_USUARIOS_NO_VERIFICADOS',

  // Roles
  ROLES_VER = 'ROLES_VER',
  ROLES_CREAR = 'ROLES_CREAR',
  ROLES_EDITAR = 'ROLES_EDITAR',
  ROLES_ELIMINAR = 'ROLES_ELIMINAR',
  ROLES_ASIGNAR_PERMISOS = 'ROLES_ASIGNAR_PERMISOS',

  PERMISOS_VER = 'PERMISOS_VER',
  PERMISOS_CREAR = 'PERMISOS_CREAR',
  PERMISOS_EDITAR = 'PERMISOS_EDITAR',
  PERMISOS_ELIMINAR = 'PERMISOS_ELIMINAR',

  // Empleados
  EMPLEADOS_VER = 'EMPLEADOS_VER',
  EMPLEADOS_CREAR = 'EMPLEADOS_CREAR',
  EMPLEADOS_EDITAR = 'EMPLEADOS_EDITAR',
  EMPLEADOS_ELIMINAR = 'EMPLEADOS_ELIMINAR',
  EMPLEADOS_ASIGNAR_SUCURSAL = 'EMPLEADOS_ASIGNAR_SUCURSAL',

  CONFIGURACION_VER = 'CONFIGURACION_VER',
  CONFIGURACION_EDITAR = 'CONFIGURACION_EDITAR',

  // ==========================
  // Admin - Catálogo
  // ==========================
  CATEGORIAS_VER = 'CATEGORIAS_VER',
  CATEGORIAS_CREAR = 'CATEGORIAS_CREAR',
  CATEGORIAS_EDITAR = 'CATEGORIAS_EDITAR',
  CATEGORIAS_ELIMINAR = 'CATEGORIAS_ELIMINAR',

  TIPOS_PRODUCTO_VER = 'TIPOS_PRODUCTO_VER',
  TIPOS_PRODUCTO_CREAR = 'TIPOS_PRODUCTO_CREAR',
  TIPOS_PRODUCTO_EDITAR = 'TIPOS_PRODUCTO_EDITAR',
  TIPOS_PRODUCTO_ELIMINAR = 'TIPOS_PRODUCTO_ELIMINAR',

  BANCOS_VER = 'BANCOS_VER',
  BANCOS_CREAR = 'BANCOS_CREAR',
  BANCOS_EDITAR = 'BANCOS_EDITAR',
  BANCOS_ELIMINAR = 'BANCOS_ELIMINAR',

  CUENTAS_BANCARIAS_VER = 'CUENTAS_BANCARIAS_VER',
  CUENTAS_BANCARIAS_CREAR = 'CUENTAS_BANCARIAS_CREAR',
  CUENTAS_BANCARIAS_EDITAR = 'CUENTAS_BANCARIAS_EDITAR',
  CUENTAS_BANCARIAS_ELIMINAR = 'CUENTAS_BANCARIAS_ELIMINAR',

  // ==========================
  // Admin - Reportes
  // ==========================
  REPORTES_VER = 'REPORTES_VER',
}
