export enum PermisoEnum {
  // ==========================
  // Admin - Seguridad
  // ==========================
  USUARIOS_VER = 'USUARIOS_VER',
  USUARIOS_CREAR = 'USUARIOS_CREAR',
  USUARIOS_EDITAR = 'USUARIOS_EDITAR',
  USUARIOS_EDITAR_CONTRASENIA = 'USUARIOS_EDITAR_CONTRASENIA',
  USUARIOS_ELIMINAR = 'USUARIOS_ELIMINAR',
  ELIMINAR_USUARIOS_NO_VERIFICADOS = 'ELIMINAR_USUARIOS_NO_VERIFICADOS',

  // Roles
  ROLES_VER = 'ROLES_VER',
  ROLES_CREAR = 'ROLES_CREAR',
  ROLES_EDITAR = 'ROLES_EDITAR',
  ROLES_ELIMINAR = 'ROLES_ELIMINAR',
  ROLES_ASIGNAR_PERMISOS = 'ROLES_ASIGNAR_PERMISOS',

  PERMISOS_VER = 'PERMISOS_VER',
  PERMISOS_CREAR = 'PERMISOS_CREAR',
  PERMISOS_EDITAR = 'PERMISOS_EDITAR',
  PERMISOS_ELIMINAR = 'PERMISOS_ELIMINAR',

  CONFIGURACION_VER = 'CONFIGURACION_VER',
  CONFIGURACION_EDITAR = 'CONFIGURACION_EDITAR',

  // Notificaciones
  NOTIFICACIONES_VER = 'NOTIFICACIONES_VER',
  NOTIFICACIONES_CREAR = 'NOTIFICACIONES_CREAR',
  NOTIFICACIONES_EDITAR = 'NOTIFICACIONES_EDITAR',
  NOTIFICACIONES_ELIMINAR = 'NOTIFICACIONES_ELIMINAR',

  // FAQs
  FAQS_VER = 'FAQS_VER',
  FAQS_CREAR = 'FAQS_CREAR',
  FAQS_EDITAR = 'FAQS_EDITAR',
  FAQS_ELIMINAR = 'FAQS_ELIMINAR',

  // ==========================
  // Admin - Catálogo
  // ==========================
  TIPOS_TRAMITE_VER = 'TIPOS_TRAMITE_VER',
  TIPOS_TRAMITE_CREAR = 'TIPOS_TRAMITE_CREAR',
  TIPOS_TRAMITE_EDITAR = 'TIPOS_TRAMITE_EDITAR',
  TIPOS_TRAMITE_ELIMINAR = 'TIPOS_TRAMITE_ELIMINAR',

  BANCOS_VER = 'BANCOS_VER',
  BANCOS_CREAR = 'BANCOS_CREAR',
  BANCOS_EDITAR = 'BANCOS_EDITAR',
  BANCOS_ELIMINAR = 'BANCOS_ELIMINAR',

  CUENTAS_BANCARIAS_VER = 'CUENTAS_BANCARIAS_VER',
  CUENTAS_BANCARIAS_CREAR = 'CUENTAS_BANCARIAS_CREAR',
  CUENTAS_BANCARIAS_EDITAR = 'CUENTAS_BANCARIAS_EDITAR',
  CUENTAS_BANCARIAS_ELIMINAR = 'CUENTAS_BANCARIAS_ELIMINAR',

  // Tipos de Documento
  TIPOS_DOCUMENTO_VER = 'TIPOS_DOCUMENTO_VER',
  TIPOS_DOCUMENTO_CREAR = 'TIPOS_DOCUMENTO_CREAR',
  TIPOS_DOCUMENTO_EDITAR = 'TIPOS_DOCUMENTO_EDITAR',
  TIPOS_DOCUMENTO_ELIMINAR = 'TIPOS_DOCUMENTO_ELIMINAR',

  // Plantillas de Documento
  PLANTILLAS_DOCUMENTO_VER = 'PLANTILLAS_DOCUMENTO_VER',
  PLANTILLAS_DOCUMENTO_CREAR = 'PLANTILLAS_DOCUMENTO_CREAR',
  PLANTILLAS_DOCUMENTO_EDITAR = 'PLANTILLAS_DOCUMENTO_EDITAR',
  PLANTILLAS_DOCUMENTO_ELIMINAR = 'PLANTILLAS_DOCUMENTO_ELIMINAR',

  // Estados de Trámite
  ESTADOS_TRAMITE_VER = 'ESTADOS_TRAMITE_VER',
  ESTADOS_TRAMITE_CREAR = 'ESTADOS_TRAMITE_CREAR',
  ESTADOS_TRAMITE_EDITAR = 'ESTADOS_TRAMITE_EDITAR',
  ESTADOS_TRAMITE_ELIMINAR = 'ESTADOS_TRAMITE_ELIMINAR',

  // Sucursales
  SUCURSALES_VER = 'SUCURSALES_VER',
  SUCURSALES_CREAR = 'SUCURSALES_CREAR',
  SUCURSALES_EDITAR = 'SUCURSALES_EDITAR',
  SUCURSALES_ELIMINAR = 'SUCURSALES_ELIMINAR',

  // Comercializadoras
  COMERCIALIZADORAS_VER = 'COMERCIALIZADORAS_VER',
  COMERCIALIZADORAS_CREAR = 'COMERCIALIZADORAS_CREAR',
  COMERCIALIZADORAS_EDITAR = 'COMERCIALIZADORAS_EDITAR',
  COMERCIALIZADORAS_ELIMINAR = 'COMERCIALIZADORAS_ELIMINAR',

  // ==========================
  // Admin - Clientes
  // ==========================
  CLIENTES_VER = 'CLIENTES_VER',
  CLIENTES_CREAR = 'CLIENTES_CREAR',
  CLIENTES_EDITAR = 'CLIENTES_EDITAR',
  CLIENTES_ELIMINAR = 'CLIENTES_ELIMINAR',

  // ==========================
  // Admin - Servicios
  // ==========================
  SERVICIOS_VER = 'SERVICIOS_VER',
  SERVICIOS_CREAR = 'SERVICIOS_CREAR',
  SERVICIOS_EDITAR = 'SERVICIOS_EDITAR',
  SERVICIOS_ELIMINAR = 'SERVICIOS_ELIMINAR',

  // Historial Estados Servicio
  HISTORIAL_ESTADOS_SERVICIO_VER = 'HISTORIAL_ESTADOS_SERVICIO_VER',
  HISTORIAL_ESTADOS_SERVICIO_CREAR = 'HISTORIAL_ESTADOS_SERVICIO_CREAR',
  HISTORIAL_ESTADOS_SERVICIO_EDITAR = 'HISTORIAL_ESTADOS_SERVICIO_EDITAR',
  HISTORIAL_ESTADOS_SERVICIO_ELIMINAR = 'HISTORIAL_ESTADOS_SERVICIO_ELIMINAR',

  // Responsables de Servicio
  RESPONSABLES_SERVICIO_VER = 'RESPONSABLES_SERVICIO_VER',
  RESPONSABLES_SERVICIO_CREAR = 'RESPONSABLES_SERVICIO_CREAR',
  RESPONSABLES_SERVICIO_EDITAR = 'RESPONSABLES_SERVICIO_EDITAR',
  RESPONSABLES_SERVICIO_ELIMINAR = 'RESPONSABLES_SERVICIO_ELIMINAR',

  // Derivaciones de Servicio
  DERIVACIONES_SERVICIO_VER = 'DERIVACIONES_SERVICIO_VER',
  DERIVACIONES_SERVICIO_CREAR = 'DERIVACIONES_SERVICIO_CREAR',
  DERIVACIONES_SERVICIO_EDITAR = 'DERIVACIONES_SERVICIO_EDITAR',
  DERIVACIONES_SERVICIO_ELIMINAR = 'DERIVACIONES_SERVICIO_ELIMINAR',

  // ==========================
  // Admin - Finanzas
  // ==========================
  // Pagos e Ingresos
  PAGOS_INGRESOS_VER = 'PAGOS_INGRESOS_VER',
  PAGOS_INGRESOS_CREAR = 'PAGOS_INGRESOS_CREAR',
  PAGOS_INGRESOS_EDITAR = 'PAGOS_INGRESOS_EDITAR',
  PAGOS_INGRESOS_ELIMINAR = 'PAGOS_INGRESOS_ELIMINAR',

  // Gastos
  GASTOS_VER = 'GASTOS_VER',
  GASTOS_CREAR = 'GASTOS_CREAR',
  GASTOS_EDITAR = 'GASTOS_EDITAR',
  GASTOS_ELIMINAR = 'GASTOS_ELIMINAR',

  // Transacciones de Egresos
  TRANSACCIONES_EGRESOS_VER = 'TRANSACCIONES_EGRESOS_VER',
  TRANSACCIONES_EGRESOS_CREAR = 'TRANSACCIONES_EGRESOS_CREAR',
  TRANSACCIONES_EGRESOS_EDITAR = 'TRANSACCIONES_EGRESOS_EDITAR',
  TRANSACCIONES_EGRESOS_ELIMINAR = 'TRANSACCIONES_EGRESOS_ELIMINAR',

  // Arqueos Diarios
  ARQUEOS_DIARIOS_VER = 'ARQUEOS_DIARIOS_VER',
  ARQUEOS_DIARIOS_CREAR = 'ARQUEOS_DIARIOS_CREAR',
  ARQUEOS_DIARIOS_EDITAR = 'ARQUEOS_DIARIOS_EDITAR',
  ARQUEOS_DIARIOS_ELIMINAR = 'ARQUEOS_DIARIOS_ELIMINAR',

  // ==========================
  // Admin - Contacto
  // ==========================
  MENSAJES_CONTACTO_VER = 'MENSAJES_CONTACTO_VER',
  MENSAJES_CONTACTO_CREAR = 'MENSAJES_CONTACTO_CREAR',
  MENSAJES_CONTACTO_EDITAR = 'MENSAJES_CONTACTO_EDITAR',
  MENSAJES_CONTACTO_ELIMINAR = 'MENSAJES_CONTACTO_ELIMINAR',

  // ==========================
  // Admin - Reportes
  // ==========================
  REPORTES_VER = 'REPORTES_VER',

  // ==========================
  // Admin - Logs y Auditoría
  // ==========================
  LOGS_VER = 'LOGS_VER',
  LOGS_EXPORTAR = 'LOGS_EXPORTAR',
}
